name: Generate Table of Game
on:
  workflow_run:
    workflows:
      ['Update JSON file game information']
    types: [completed]
  workflow_dispatch:

jobs:
  generate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: Generate Table
        run:
            python scripts/generate_md.py

      - name: Debug ls
        run: |
          ls -la
          
      - name: Commit and push if changed
        run: |
          git config --global user.name "poli0981"
          git config --global user.email "127664709+poli0981@users.noreply.github.com"
          git add lists/*.md
          git status
          if git diff --cached --quiet; then
            echo "No diff detected"
            git commit --allow-empty -m "Auto regenerate tables (timestamp update) [$(date +'%Y-%m-%d %H:%M')]" || echo "Empty commit skip"
          else
            git commit -m "Auto regenerate tables from data.json [$(date +'%Y-%m-%d %H:%M')]"
          fi
            git push || echo "Push fail – check token/permission bro"
