name: Generate Table of Game
on:
  workflow_run:
    workflows:
      ['Update JSON file game information']
    types: [completed]
  workflow_dispatch:

permissions:
    contents: write

jobs:
  generate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: Run bash script to generate table
        run: |
          chmod +x ./bash/table.sh
          ./bash/table.sh
        shell: bash
