name: Update JSON file game information
on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 03:00 UTC
  workflow_dispatch:

permissions:
    contents: write

jobs:
  update-game-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: Run bash script to update game info
        run: |
            chmod +x ./bash/test.sh
            ./bash/test.sh
        shell: bash
